stages:
 - build
 - package
 - staging
 - production

# For more information on Maven see
#  https://gitlab.com/gitlab-org/gitlab-ci-yml/blob/master/Maven.gitlab-ci.yml

# For more information on Docker see
#  https://gitlab.com/gitlab-org/gitlab-ci-yml/blob/master/Docker.gitlab-ci.yml


build:maven:
  image: maven:3.3.9-jdk-8
  stage: build
  variables:
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
    MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  script:
    - mvn $MAVEN_CLI_OPTS clean package
    - cat target/site/jacoco/index.html
  tags:
    - kubernetes
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - .m2/repository
  artifacts:
    paths:
      - target/network-map-service.jar
      - target/site/jacoco/index.html

package:docker:
  stage: package
  variables:
    DOCKER_HOST: tcp://localhost:2375
  services:
    - docker:dind
  image: docker:latest
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t ${CI_REGISTRY_IMAGE}/${CI_PROJECT_NAME}:${CI_PIPELINE_ID} .
    - docker tag ${CI_REGISTRY_IMAGE}/${CI_PROJECT_NAME}:${CI_PIPELINE_ID} ${CI_REGISTRY_IMAGE}/${CI_PROJECT_NAME}:latest
    - docker push ${CI_REGISTRY_IMAGE}/${CI_PROJECT_NAME}:${CI_PIPELINE_ID}
    - docker push ${CI_REGISTRY_IMAGE}/${CI_PROJECT_NAME}:latest
  tags:
    - kubernetes
  only:
    - master

deploy:edge:
  image: lachlanevenson/k8s-kubectl
  stage: staging
  script:
    - kubectl config current-context
    - kubectl 
    - kubectl set image deployment/${CI_ENVIRONMENT_SLUG} network-map-service=${CI_REGISTRY_IMAGE}/${CI_PROJECT_NAME}:${CI_PIPELINE_ID}
  tags:
    - kubernetes
  environment:
    name: network-map-edge
    url: https://network-map-edge.cordite.biz
  only:
    - master
  
rebuild:edge:
  image: lachlanevenson/k8s-kubectl
  stage: staging
  script:
    - kubectl config current-context
    - cd deployment
    - ./kube_deploy.sh
  tags:
    - kubernetes
  environment:
    name: network-map-edge
    url: https://network-map-edge.cordite.biz
  only:
    - master
  when:
    manual

deploy:live:
  image: lachlanevenson/k8s-kubectl
  stage: production
  script:
    - kubectl config current-context
    - kubectl set image deployment/${CI_ENVIRONMENT_SLUG} network-map-service=${CI_REGISTRY_IMAGE}/${CI_PROJECT_NAME}:${CI_PIPELINE_ID}
  tags:
    - kubernetes
  environment:
    name: network-map
    url: https://network-map-edge.cordite.biz
  only:
    - master
  when:
    manual

rebuild:live:
  image: lachlanevenson/k8s-kubectl
  stage: production
  script:
    - kubectl config current-context
    - cd deployment
    - ./kube_deploy.sh
  tags:
    - kubernetes
  environment:
    name: network-map
    url: https://network-map.cordite.biz
  only:
    - master
  when:
    manual