apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: network-map-dev
  labels:
    app: network-map-dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: network-map-dev
    spec:
      containers:
        - name: network-map-dev
          image: registry.gitlab.com/cordite/network-map-service/network-map-service:latest
          env:
            - name: NMS_PORT
              value: "80"
            - name: NMS_NOTARY_DIR
              value: "/mnt/cordite/alpha/nms/validating-notaries"
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: gitlab-registry
---
apiVersion: v1
kind: Service
metadata:
  name: network-map-dev
  annotations:
    external-dns.alpha.kubernetes.io/hostname: network-map-dev.cordite.biz
spec:
  selector:
    app: network-map-dev
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80