apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-nginx
spec:
  tls:
  # This assumes tls-secret exists.
  - secretName: tls-secret
  rules:
  - http:
      paths:
      - backend:
          # This assumes network-map-service exists and routes to healthy endpoints.
          serviceName: network-map-service
          servicePort: 80